"""initial_migration

Revision ID: 4b03b0885be6
Revises: 
Create Date: 2026-07-29 21:17:23.384544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4b03b0885be6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('hostel', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("hostel IN ('Asrama Putera', 'Asrama Puteri') OR hostel IS NULL", name='ck_users_hostel'),
    sa.CheckConstraint("role IN ('admin', 'warden')", name='ck_users_role'),
    sa.CheckConstraint("status IN ('active', 'revoked')", name='ck_users_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refresh_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('idx_refresh_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hostel', sa.String(length=20), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('duty_warden_id', sa.UUID(), nullable=False),
    sa.Column('is_substitution', sa.Boolean(), nullable=False),
    sa.Column('inspection_time', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flagged_by', sa.UUID(), nullable=True),
    sa.Column('flagged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_note', sa.Text(), server_default='', nullable=False),
    sa.Column('aduan_kerosakan', sa.Text(), server_default='TKD', nullable=False),
    sa.Column('murid_sakit', sa.Text(), server_default='TLB', nullable=False),
    sa.Column('kawalan_keselamatan', sa.SmallInteger(), nullable=True),
    sa.Column('catatan_tambahan', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("hostel IN ('Asrama Putera', 'Asrama Puteri')", name='ck_reports_hostel'),
    sa.CheckConstraint("status IN ('draft', 'submitted', 'reviewed', 'flagged')", name='ck_reports_status'),
    sa.CheckConstraint('kawalan_keselamatan BETWEEN 1 AND 5 OR kawalan_keselamatan IS NULL', name='ck_reports_security'),
    sa.ForeignKeyConstraint(['duty_warden_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['flagged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'hostel', name='uq_reports_date_hostel')
    )
    op.create_index('idx_reports_date', 'reports', ['date'], unique=False)
    op.create_index('idx_reports_duty_warden', 'reports', ['duty_warden_id'], unique=False)
    op.create_index('idx_reports_hostel', 'reports', ['hostel'], unique=False)
    op.create_index('idx_reports_status', 'reports', ['status'], unique=False)
    op.create_index('idx_reports_submitted_by', 'reports', ['submitted_by'], unique=False)
    op.create_table('roster',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('putera_warden_id', sa.UUID(), nullable=False),
    sa.Column('puteri_warden_id', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['putera_warden_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['puteri_warden_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_index('idx_roster_date', 'roster', ['date'], unique=False)
    op.create_table('approval_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("action IN ('created', 'submitted', 'reviewed', 'flagged')", name='ck_approval_action'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_approval_report', 'approval_log', ['report_id'], unique=False)
    op.create_table('report_ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.String(length=50), nullable=False),
    sa.Column('item_key', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.String(length=2), nullable=True),
    sa.CheckConstraint("rating IN ('1','2','3','4','NA','') OR rating IS NULL", name='ck_ratings_value'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'section_id', 'item_key', name='uq_ratings_item')
    )
    op.create_index('idx_ratings_report', 'report_ratings', ['report_id'], unique=False)
    op.create_index('idx_ratings_section', 'report_ratings', ['report_id', 'section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ratings_section', table_name='report_ratings')
    op.drop_index('idx_ratings_report', table_name='report_ratings')
    op.drop_table('report_ratings')
    op.drop_index('idx_approval_report', table_name='approval_log')
    op.drop_table('approval_log')
    op.drop_index('idx_roster_date', table_name='roster')
    op.drop_table('roster')
    op.drop_index('idx_reports_submitted_by', table_name='reports')
    op.drop_index('idx_reports_status', table_name='reports')
    op.drop_index('idx_reports_hostel', table_name='reports')
    op.drop_index('idx_reports_duty_warden', table_name='reports')
    op.drop_index('idx_reports_date', table_name='reports')
    op.drop_table('reports')
    op.drop_index('idx_refresh_user', table_name='refresh_tokens')
    op.drop_index('idx_refresh_hash', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
